#!/usr/bin/env node

import prompts from 'prompts';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface Config {
  projectName: string;
  facilitatorUrl: string;
  facilitatorPublicKey: string;
  port: string;
  install: boolean;
  packageManager: 'npm' | 'bun' | 'yarn' | 'pnpm';
}

function generateRandomSecret(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < 32; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

function detectPackageManager(): 'npm' | 'bun' | 'yarn' | 'pnpm' {
  try {
    execSync('bun --version', { stdio: 'ignore' });
    return 'bun';
  } catch {
    try {
      execSync('pnpm --version', { stdio: 'ignore' });
      return 'pnpm';
    } catch {
      try {
        execSync('yarn --version', { stdio: 'ignore' });
        return 'yarn';
      } catch {
        return 'npm';
      }
    }
  }
}

async function main() {
  console.log(chalk.bold.cyan('\n🚀 x402-Teller Dashboard Setup\n'));

  const args = process.argv.slice(2);
  const targetDirArg = args[0];

  const config = await prompts([
    {
      type: targetDirArg ? null : 'text',
      name: 'projectName',
      message: 'Project name:',
      initial: 'x402-dashboard',
      validate: (value) => {
        if (!value) return 'Project name is required';
        if (!/^[a-z0-9-_]+$/i.test(value)) {
          return 'Project name can only contain letters, numbers, hyphens, and underscores';
        }
        return true;
      }
    },
    {
      type: 'text',
      name: 'facilitatorUrl',
      message: 'Facilitator API URL:',
      initial: 'http://localhost:3000',
      validate: (value) => {
        try {
          new URL(value);
          return true;
        } catch {
          return 'Please enter a valid URL';
        }
      }
    },
    {
      type: 'text',
      name: 'facilitatorPublicKey',
      message: 'Facilitator Solana public key:',
      validate: (value) => value.length > 0 || 'Public key is required'
    },
    {
      type: 'text',
      name: 'port',
      message: 'Dashboard port:',
      initial: '3001',
      validate: (value) => {
        const port = parseInt(value, 10);
        if (isNaN(port) || port < 1 || port > 65535) {
          return 'Please enter a valid port number (1-65535)';
        }
        return true;
      }
    },
    {
      type: 'confirm',
      name: 'install',
      message: 'Install dependencies now?',
      initial: true
    }
  ]) as Config;

  if (!config.facilitatorPublicKey) {
    console.log(chalk.red('\n❌ Setup cancelled'));
    process.exit(1);
  }

  config.projectName = targetDirArg || config.projectName;
  config.packageManager = detectPackageManager();

  const targetDir = path.resolve(process.cwd(), config.projectName);

  // Check if directory exists
  if (fs.existsSync(targetDir)) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: `Directory ${chalk.cyan(config.projectName)} already exists. Overwrite?`,
      initial: false
    });

    if (!overwrite) {
      console.log(chalk.red('\n❌ Setup cancelled'));
      process.exit(1);
    }

    fs.removeSync(targetDir);
  }

  // Create directory
  const spinner = ora('Creating project directory...').start();
  fs.ensureDirSync(targetDir);
  spinner.succeed('Project directory created');

  // Copy template files
  spinner.start('Copying dashboard files...');
  const templateDir = path.join(__dirname, '..', 'template');

  // Check if we're in development (template in packages/ui) or production (template in CLI package)
  const uiSourceDir = path.join(__dirname, '..', '..', 'ui');
  const sourceDir = fs.existsSync(templateDir) ? templateDir : uiSourceDir;

  try {
    // Copy all files except node_modules, .next, and .env files
    fs.copySync(sourceDir, targetDir, {
      filter: (src) => {
        const relativePath = path.relative(sourceDir, src);
        return !relativePath.includes('node_modules') &&
               !relativePath.includes('.next') &&
               !relativePath.includes('dist') &&
               !relativePath.startsWith('.env');
      }
    });
    spinner.succeed('Dashboard files copied');
  } catch (error) {
    spinner.fail('Failed to copy dashboard files');
    console.error(chalk.red(error));
    process.exit(1);
  }

  // Generate .env.local
  spinner.start('Generating configuration...');
  const envContent = `# x402-Teller Dashboard Configuration
# Generated by create-x402-dashboard

# NextAuth Configuration
NEXTAUTH_SECRET=${generateRandomSecret()}
NEXTAUTH_URL=http://localhost:${config.port}

# Facilitator Configuration
FACILITATOR_API_URL=${config.facilitatorUrl}
NEXT_PUBLIC_FACILITATOR_PUBLIC_KEY=${config.facilitatorPublicKey}
`;

  fs.writeFileSync(path.join(targetDir, '.env.local'), envContent);
  spinner.succeed('Configuration generated');

  // Install dependencies
  if (config.install) {
    spinner.start(`Installing dependencies with ${config.packageManager}...`);
    try {
      const installCmd = config.packageManager === 'npm' ? 'npm install' :
                        config.packageManager === 'yarn' ? 'yarn' :
                        config.packageManager === 'pnpm' ? 'pnpm install' :
                        'bun install';

      execSync(installCmd, {
        cwd: targetDir,
        stdio: 'ignore'
      });
      spinner.succeed('Dependencies installed');
    } catch (error) {
      spinner.fail('Failed to install dependencies');
      console.log(chalk.yellow('\n⚠️  You can install them manually later'));
    }
  }

  // Success message
  console.log(chalk.green.bold('\n✅ Dashboard scaffolded successfully!\n'));
  console.log(chalk.bold('📂 Location:'), chalk.cyan(targetDir));
  console.log(chalk.bold('🔑 Config:'), chalk.cyan('.env.local'), '(created)\n');

  console.log(chalk.bold('📝 Next steps:\n'));
  console.log(chalk.cyan(`  cd ${config.projectName}`));
  if (!config.install) {
    console.log(chalk.cyan(`  ${config.packageManager} install`));
  }
  console.log(chalk.cyan(`  ${config.packageManager === 'npm' ? 'npm run' : config.packageManager} dev`));
  console.log(chalk.dim(`\n  Dashboard will be available at http://localhost:${config.port}`));

  console.log(chalk.bold('\n🔐 Authentication:\n'));
  console.log(chalk.dim('  Sign in with your facilitator wallet to access the dashboard'));
  console.log(chalk.dim('  Only the facilitator wallet owner can view transaction data\n'));
}

main().catch((error) => {
  console.error(chalk.red('Error:'), error);
  process.exit(1);
});
